Frebdump
jpdsi/blog pull request #4
Opened 2021-05-24 00:21 UTC by georgioush

I've created FREBDump articles. I'd like you to check them and merge if they have no problem,

2021-05-26 11:02 UTC, nt-7 requested changes

2021-05-26 11:02 UTC, nt-7 commented on articles/web-apps/freb.md
> +![FREB の規則作成手順図](./frebdump/frebdump_2021-05-20-01-17-01.png)
This relative path is wrong. 
You should change to **..**/frebdump/frebdump_2021-05-20-01-17-01.png.

![image](https://user-images.githubusercontent.com/20683785/119647550-5c040200-be5b-11eb-87e2-b71fc5a69993.png)

2021-05-26 11:02 UTC, nt-7 commented on articles/web-apps/frebdump.md
> +FREBDump とは、ProcDump の一種で、失敗した要求トレース (通称: FREB ) を契機として ProcDump を実行します。
There is an extra space after the string "FREB".

2021-05-26 11:02 UTC, nt-7 commented on articles/web-apps/frebdump-faq.md
> +title: 失敗した要求トレースを契機とするメモリダンプ (FREBDump) のよくいただくご質問について
This title should be in the format of [IE モードのよくあるご質問](https://jpdsi.github.io/blog/internet-explorer-microsoft-edge/ie-mode-faq/).
e.g.) "失敗した要求トレースを契機とするメモリダンプ (FREBDump) のよく**あるご質問**"

2021-05-26 11:32 UTC, atsushina commented on articles/web-apps/freb.md
> +なお注意点として [トレース] 機能をサーバーの機能としてインストールしていない場合、インストール時にサーバーの再起動が必要になります。
サーバー自体の再起動を求められることは無いはずです。ワーカー プロセスが再起動されるので考慮してね、ぐらいがいいかと

2021-05-26 11:46 UTC, atsushina commented on articles/web-apps/frebdump.md
> +FREBDump とは、ProcDump の一種で、失敗した要求トレース (通称: FREB ) を契機として ProcDump を実行します。
あとは、FREB Dump は Procdump の一種ではないので、その記載は削除でいいかなと

2021-05-26 11:48 UTC, atsushina commented on articles/web-apps/frebdump.md
> +[場所] が <対象となるウェブサイト>.config になっていることを確認してください。
「<対象となるウェブサイト>.config」ではなくて、「<対象となるウェブサイト> Web.config」かと

2021-05-26 12:08 UTC, nt-7 reviewed
Test comment review

2021-05-26 15:03 UTC, georgioush commented on articles/web-apps/freb.md
> +![FREB の規則作成手順図](./frebdump/frebdump_2021-05-20-01-17-01.png)
これは単純に freb の画像を frebdump から流用したからですね、修正します。

2021-05-26 15:03 UTC, georgioush commented on articles/web-apps/frebdump.md
> +FREBDump とは、ProcDump の一種で、失敗した要求トレース (通称: FREB ) を契機として ProcDump を実行します。
修正します！

2021-05-27 00:30 UTC, georgioush commented on articles/web-apps/frebdump-faq.md
> +title: 失敗した要求トレースを契機とするメモリダンプ (FREBDump) のよくいただくご質問について
修正します！

2021-05-27 00:30 UTC, georgioush commented on articles/web-apps/freb.md
> +なお注意点として [トレース] 機能をサーバーの機能としてインストールしていない場合、インストール時にサーバーの再起動が必要になります。
修正します！

2021-05-27 00:31 UTC, georgioush commented on articles/web-apps/frebdump.md
> +[場所] が <対象となるウェブサイト>.config になっていることを確認してください。
画像も含めて治します！

2021-05-27 00:31 UTC, georgioush commented
ご指摘いただいた部分の修正を行いました。また日時も今日に変更しました。ご確認いただけますと幸いです @atsushina @nt-7

2021-05-28 12:19 UTC, nt-7 approved these changes
LGTM

2021-05-28 13:17 UTC, merged