Debugdiag
jpdsi/blog pull request #5
Opened 2021-05-30 10:06 UTC by georgioush

すでに DebugDiag の記事は以下にございます。
https://jpdsi.github.io/blog/web-apps/LogCollection4/

ただ、画像やより詳細な説明を追加しました。
また今後の記事を発展させて 2nd Chance について記事をヘッダーに追加する場合でも問題ない構成にしました。

またウェブサイトの命名規則として LogCollection4 よりも、debugdiag のほうが直感的にわかりやすいことから、こちらに新しくページを作成し、LogCollection4 のページに新規ページへのリンクを貼るように設定しました。

ご添削いただけますと幸いです。

2021-06-15 10:24 UTC, nt-7 requested changes
こちらいくつかコメントを追記しました。どうぞよろしくお願いいたします。

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/LogCollection4.md
> +- DebugDiag の取得方法について :  https://jpdsi.github.io/blog/debugdiag/
正式名 Debug Diagnostics Tool を利用した方がより良いですね。後述で DebugDiag と略した形で記載したい場合は () 括弧書きで書いておきましょう。

eg) Debug Diagnostics Tool (DebugDiag) の取得方法について

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +今回は DebugDiag によりメモリダンプを取得する手順についてご説明いたします。
こちらも上部コメントと同様です。1 つ目なので () 書きで書いておいて、以降 DebugDiag で記載する形で。

eg) 今回は Debug Diagnostics Tool (DebugDiag) によりメモリダンプを取得する手順についてご説明いたします。

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +取得するメモリの領域の指定は以下 2 つ可能です。なお通常、お問い合わせの調査には User Fulldump の取得をお願いしております。
この文章の助詞は以下の感じがよいかと。
eg) 取得するメモリの領域の指定は以下**の** 2 つ**が**可能です。

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +- イベントログに記録された文字列を発火点として取得する
発火点の部分を修正
eg) イベントログに記録された文字列を**起点**として取得する

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +- 64bit 版の Debug Diag : [Debug Diagnostic Tool v2 Update 3](http://debugdiag.com/)
@atsushina 64 bit も 32bit も以下は対応していた気がしますが念の為ご確認いただけますでしょうか。
https://www.microsoft.com/en-us/download/details.aspx?id=102635

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +弊社より指示がない場合は、画像のように Access Violation による例外発生によるダンプの取得を行います。
こちら何でもアクセス違反で取得するように見受けられなくはないので、例えば以下のように変えましょう。
eg) 今回はアクセス違反発生時にダンプを取得する例を紹介します。以下の画像のように Access Violation による例外発生によるダンプの取得を行います。

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +特に弊社から <検証用の例外コード> に指定がない場合は 0xC0000005 の例外コードを 10 進数表示した 3221225477 こちらを指定してください。
こちらも上部のコメントと同様ですね。

**before** : 特に弊社から <検証用の例外コード> に指定がない場合は 0xC0000005 の例外コードを...
**after** : 今回は例としてアクセス違反の例外を意図的に発生させます。具体的にはアクセス違反の 0xC0000005 の例外コードを 10 進数表示した 3221225477 こちらを指定してください。

2021-06-15 10:24 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +
こちら念の為最後に注釈として、例えば簡単に以下のような注意事項を入れておくとよいと思います。
※ なお、Debug Diagnostic Tool ツール自体のサポートは私共技術サポートではご提供しておりません。そのため、上記ツールのトラブルシューティングやツールの詳細なご紹介等はご支援できませんことご了承ください。

2021-06-15 10:41 UTC, atsushina commented on articles/web-apps/debugdiag.md
> +- 64bit 版の Debug Diag : [Debug Diagnostic Tool v2 Update 3](http://debugdiag.com/)
大嶋君が記載したので合ってます。なので、OS が 64bit なら、アプリケーション プールの bit 数に関わらず 64bit 版の DebugDiag を使ってください。

なお、32bit 版の DebugDiag は 32bit OS 用に残されています。これは一応 Win10 には x86 版があるからですが、今はほとんど使われることが無いかと。

2021-06-27 04:21 UTC, georgioush commented on articles/web-apps/debugdiag.md
> +- 64bit 版の Debug Diag : [Debug Diagnostic Tool v2 Update 3](http://debugdiag.com/)
@atsushina  とすると 32bit アプリケーションの有効化云々は関係ないという認識でよいでしょうか？

```
ダンプを生成したい対象となるサイトのアプリケーションプールが [32ビット アプリケーションの有効化] を true にしている場合は、32 bit 版をダウンロードします。
```

2021-06-27 04:25 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +- 64bit 版の Debug Diag : [Debug Diagnostic Tool v2 Update 3](http://debugdiag.com/)
@georgioush 代わりに回答しますが、関係ない認識であってます。つまり、基本的に 64bit 版の Debug Diag を利用してもらうで問題ないです。

2021-06-28 00:08 UTC, georgioush commented on articles/web-apps/LogCollection4.md
> +- DebugDiag の取得方法について :  https://jpdsi.github.io/blog/debugdiag/
修正しました。

2021-06-28 00:08 UTC, georgioush commented on articles/web-apps/debugdiag.md
> +今回は DebugDiag によりメモリダンプを取得する手順についてご説明いたします。
修正しました。

2021-06-28 00:09 UTC, georgioush commented on articles/web-apps/debugdiag.md
> +取得するメモリの領域の指定は以下 2 つ可能です。なお通常、お問い合わせの調査には User Fulldump の取得をお願いしております。
修正しました。

2021-06-28 00:09 UTC, georgioush commented
こちら再度修正済みましたのでご確認いただけますと幸いですm(_ _)m

2021-06-28 10:46 UTC, nt-7 requested changes
1 点だけ。その他 LGTM です。

2021-06-28 10:46 UTC, nt-7 commented on articles/web-apps/debugdiag.md
> +※ OS が 32bit 版のみ 32bit 番の DebugDiag をインストールしてください。
32bit 番 -> 32 bit 版

2021-06-28 13:17 UTC, georgioush commented
こちら再度修正をいたしましたので、ご確認いただけますと幸いです。
問題なければ Merge したいと考えておりますm(_ _)m

2021-06-29 10:34 UTC, nt-7 approved these changes
LGTM

2021-06-29 11:24 UTC, atsushina commented on articles/web-apps/debugdiag.md
> +- [Action Type] : \<First Chance での取得するダンプの領域\>
ダンプの領域、ではなくて、ダンプの種類、ですかね。
あと、下の Action Limit と合わせて、「First Chance での」ではなくて「First Chance で」かと。

2021-06-29 11:26 UTC, atsushina commented on articles/web-apps/debugdiag.md
> +DebugDiag 自体を削除する場合は、有効化したルールすべてを削除します。
この行は不要かなと。DebugDiag をアンインストールしたら、有効化したルールを含めて削除されるので。

2021-06-29 14:00 UTC, georgioush commented
修正しました！これでマージしちゃいます！

2021-06-29 14:01 UTC, merged